name: get-open-weather
inputs:
  API_KEY:
    description: should be an openWeather API key
    required: true
  COORDINATES:
    description: should be an object '{latitude:x, longitude:x}, can also be an array of these objects. If is an array you can give each object an id for output'
    required: true
  EXCLUDE:
    description: options to exclude are "current,minutely,hourly,daily,alerts", should be in comma delimited list
    required: false
outputs:
  DATA:
    description: outputs either an array or an object depending on inputs
runs:
  using: 'node16'
  main: dist/index.js
