name: get-open-weather
inputs:
  API_KEY:
    description: should be an openWeather API key
    required: true
  DATA:
    description: "should be an stringifyed json object or array with id,longitude,latitude,city,state"
    required: false
    default: null
outputs:
  DATA:
    description: outputs either an array or an object depending on inputs
runs:
  using: "node16"
  main: dist/index.js
